name:                fphw3
version:             0.1.0.0
github:              "grifguitar/fphw3"
license:             BSD3
author:              "Khlytin Grigoriy"
maintainer:          "xlootin@gmail.com"
copyright:           "2020 Khlytin Grigoriy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/grifguitar/fphw3#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- directory
- containers
- bytestring
- filepath

library:
  source-dirs: src

executables:
  fphw3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fphw3

tests:
  fphw3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fphw3
    - tasty
    - tasty-hspec
    - tasty-hedgehog
    - hspec
    - hedgehog
    - hspec-hedgehog